### ISSUE TITLE
compile error - basic example

### ISSUE THREAD

**Issue by alwaysmohawk** [end2endzone/SoftTimers#8]
getting a compile error:

Invalid conversion from 'void (*)(uint8_t, unsigned int, long unsigned int)' {aka 'void (*)(unsigned char, unsigned int, long unsigned int)'} to 'anyrtttl::ToneFuncPtr' {aka 'void (*)(unsigned char, short unsigned int, unsigned int)'} [-fpermissive]
 ToneFuncPtr _tone = &tone;

when trying to compile the basic example, pulled latest from arduino ide, v 2.2.0

**Comment by end2endzone** [comment]
Hi. Apologize for the late reply. I think this is more related to [AnyRtttl](https://github.com/end2endzone/AnyRtttl) library than SoftTimers. Would you like to open an issue [over there](https://github.com/end2endzone/AnyRtttl/issues) ? I could add my investigation notes.

**Comment by alwaysmohawk** [comment]
dang, sure, thanks. Not sure how it went to you? sorry, i'm very new to github.
